### ISSUE TITLE
Request for linux support

### ISSUE THREAD

**Issue by emanuelebiondi** [jhelumcorp/gyawun#162] opened 2024-10-08 09:12 UTC
I love your app and its functionality on Windows! I wanted to ask if you would consider adding support for Linux. As a Linux user, I would greatly appreciate being able to use your application on my distribution.

**Comment by sheikhhaziq** [comment] 2024-10-16 05:17
right now,  the fluent_ui library is having some problems on Linux. I'll still try to find a way.

**Comment by sheikhhaziq** [comment] 2024-10-27 10:16
closing as it is duplicate of #45

**Closed by sheikhhaziq** 2024-10-27 10:16 UTC
